### ISSUE TITLE
Migrate to operator's objects

### ISSUE THREAD

**Issue by SunSince90** [CloudNativeSDWAN/cnwan-reader#25]
To be consistent and improve code re-usability, currently service registry objects **will be deprecated** and the ones defined by the operator will be used instead.

Nonetheless, this will require and update of the operator to make its service registry object "final" and reach some sort of `v1` for it.

**Comment by arnatal** [comment]
I'm not sure we should aim for anything "final/v1" for now, since there are chances that the service registry object will still be modified a few more times. Rather, we could maybe have the Reader point to particular Operator releases. For instance, when needed, we could include something like this in the Reader: "This release of the Reader deprecates support for Operator versions prior to 0.x.y. Please update your Operator to use version 0.x.y". Long term we can look into making things more final.

**Comment by SunSince90** [comment]
No this will only be for the go package that will be imported, not for the operator itself, so you can even not have the operator running anywhere. Adding things on that is fine, as long as the "agreement" that those fields (e.g. Name, NamespaceName) and their types stay like this. 

So there will be no real v1 (especially not the operator), but its service registry package will instead be in a very stable version, almost like it was a v1

**Comment by ljakab** [comment]
We will be using a common OpenAPI repo. Closing
